export const SAVE_KEY = 'WORD_SEARCH_SAVE_DATA';
export const MAX_LEVEL = 1000;
export const DEFAULT_HINT_COUNT = 3;
export const BASE_REWARD_COIN = 20;

export const LETTERS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';

export const EVENT = {
  LEVEL_STARTED: 'LEVEL_STARTED',
  WORD_FOUND: 'WORD_FOUND',
  LEVEL_COMPLETED: 'LEVEL_COMPLETED',
  SAVE_CHANGED: 'SAVE_CHANGED',
  SETTINGS_CHANGED: 'SETTINGS_CHANGED',
} as const;
